CXX = main.cpp
CXX += FibonacciR.cpp
CXX += FibonacciR.hpp
CXX += FibonacciNR.cpp
CXX += FibonacciNR.hpp

PROG1 = Fibonacci
PROGS = ${PROG1}

default:
	g++ ${CXX} -o Fibonacci

clean:
	rm -f ${PROGS} *.o *~