CXX = main.cpp
CXX += Combat.cpp
CXX += Hero.cpp
CXX += Vampire.cpp
CXX += Barbarian.cpp
CXX += BlueMen.cpp
CXX += Medusa.cpp
CXX += HarryPotter.cpp
CXX += Stack.cpp
CXX += Queue.cpp
CXX += Tournament.cpp
CXX += Combat.hpp
CXX += Hero.hpp
CXX += Vampire.hpp
CXX += Barbarian.hpp
CXX += BlueMen.hpp
CXX += Medusa.hpp
CXX += HarryPotter.hpp
CXX += Stack.hpp
CXX += Queue.hpp
CXX += Tournament.hpp

PROG1 = battle
PROGS = ${PROG1}

default:
	g++ ${CXX} -o battle

clean:
	rm -f ${PROGS} *.o *~