CXX = main.cpp
CXX += readMatrix.cpp
CXX += determinant.cpp
CXX += readMatrix.hpp
CXX += determinant.hpp

PROG1 = determinant
PROGS = ${PROG1}

default:
	g++ ${CXX} -o determinant

clean:
	rm -f ${PROGS} *.o *~