CXX = main.cpp
CXX += Die.cpp
CXX += LoadedDie.cpp
CXX += Game.cpp
CXX += Die.hpp
CXX += LoadedDie.hpp
CXX += Game.hpp

PROG1 = die
PROGS = ${PROG1}

default:
	g++ ${CXX} -o die

clean:
	rm -f ${PROGS} *.o *~